events {}

http {
    server {
        listen 80;

        location /insurance_chatbot/ {
            proxy_pass http://insurance_chatbot:8002/;
            proxy_set_header Host $host;
        }
    }
}